#!/usr/bin/env npx tsx
/**
 * Extract segment IDs from character SVG files
 * Generates a SEGMENT_MAP object for use in the LED display
 * 
 * Run with: npx tsx scripts/extract-segments.ts
 */

import { readFileSync, readdirSync, writeFileSync } from 'fs';
import { join, basename } from 'path';

const CHARS_DIR = './public/fonts/characters';

interface SegmentMap {
    [char: string]: string[];
}

// Get all 0.2.1 SVG files (both #v0.2.1 and #0.2.1 patterns, with suffixes like #approx, #guess)
const files = readdirSync(CHARS_DIR)
    .filter((f) => f.includes('0.2.1') && f.endsWith('.svg'))
    .sort();

const segmentMap: SegmentMap = {};

// Unicode to readable name mapping for common characters
const unicodeNames: Record<string, string> = {
    'U+20': 'SPACE',
    'U+21': '!',
    'U+22': '"',
    'U+23': '#',
    'U+24': '$',
    'U+25': '%',
    'U+26': '&',
    'U+27': "'",
    'U+28': '(',
    'U+29': ')',
    'U+2a': '*',
    'U+2b': '+',
    'U+2c': ',',
    'U+2d': '-',
    'U+2e': '.',
    'U+2f': '/',
    'U+3a': ':',
    'U+3b': ';',
    'U+3c': '<',
    'U+3d': '=',
    'U+3e': '>',
    'U+3f': '?',
    'U+40': '@',
    'U+5b': '[',
    'U+5c': '\\',
    'U+5d': ']',
    'U+5e': '^',
    'U+5f': '_',
    'U+60': '`',
    'U+7b': '{',
    'U+7c': '|',
    'U+7d': '}',
    'U+7e': '~',
    'U+c4': 'Ä',
    'U+d6': 'Ö',
    'U+dc': 'Ü',
    'U+df': 'ß',
    'U+2588': '█', // Full block
    'U+0298': 'ʘ', // Bilabial click
};

for (const file of files) {
    const content = readFileSync(join(CHARS_DIR, file), 'utf8');

    // Extract character from filename (before #)
    let char = basename(file).split('#')[0];

    // Handle Unicode escapes (U+xx format)
    if (char.startsWith('U+')) {
        // Check our mapping first
        if (unicodeNames[char]) {
            char = unicodeNames[char];
        } else {
            // Convert hex to character
            const codePoint = parseInt(char.slice(2), 16);
            char = String.fromCodePoint(codePoint);
        }
    }

    // Extract all path IDs (excluding non-path elements)
    const pathIds: string[] = [];
    const regex = /id="(path\d+)"/g;
    let match;
    while ((match = regex.exec(content)) !== null) {
        pathIds.push(match[1]);
    }

    if (pathIds.length > 0) {
        segmentMap[char] = pathIds;
    }
}

// Generate JavaScript output
let output = `// Auto-generated by scripts/extract-segments.ts
// Generated: ${new Date().toISOString()}
// Total characters: ${Object.keys(segmentMap).length}

export const SEGMENT_MAP: Record<string, string[]> = {
`;

for (const [char, ids] of Object.entries(segmentMap)) {
    // Escape special characters for JS string keys
    let key: string;
    if (char === "'") {
        key = '"\'\"';
    } else if (char === '\\') {
        key = "'\\\\'";
    } else {
        key = `'${char}'`;
    }
    output += `  ${key}: [${ids.map((id) => `'${id}'`).join(', ')}],\n`;
}

output += `};

// Character list for navigation (sorted by type)
export const CHARS_ALPHA = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
export const CHARS_NUMERIC = '0123456789';
export const CHARS_UMLAUT = 'ÄÖÜß';
export const CHARS_PUNCTUATION = Object.keys(SEGMENT_MAP).filter(
  (c) => !CHARS_ALPHA.includes(c) && !CHARS_NUMERIC.includes(c) && !CHARS_UMLAUT.includes(c) && c !== ' ' && c !== 'SPACE'
).join('');

export const ALL_CHARS = ' ' + CHARS_ALPHA + CHARS_NUMERIC + CHARS_UMLAUT + CHARS_PUNCTUATION;
`;

// Console output for quick reference
console.log('=== SEGMENT MAP EXTRACTION ===');
console.log(`Found ${files.length} SVG files`);
console.log(`Extracted ${Object.keys(segmentMap).length} characters:\n`);

// Group by type
const alpha = Object.keys(segmentMap).filter((c) => /^[A-Z]$/.test(c));
const numeric = Object.keys(segmentMap).filter((c) => /^[0-9]$/.test(c));
const umlaut = Object.keys(segmentMap).filter((c) => 'ÄÖÜß'.includes(c));
const punct = Object.keys(segmentMap).filter(
    (c) => !alpha.includes(c) && !numeric.includes(c) && !umlaut.includes(c)
);

console.log(`Alpha (${alpha.length}): ${alpha.join(' ')}`);
console.log(`Numeric (${numeric.length}): ${numeric.join(' ')}`);
console.log(`Umlaut (${umlaut.length}): ${umlaut.join(' ')}`);
console.log(`Punctuation (${punct.length}): ${punct.map((c) => c === ' ' ? 'SPACE' : c).join(' ')}`);

// Write to file
const outFile = './src/segment-map.ts';
writeFileSync(outFile, output);
console.log(`\nWritten to: ${outFile}`);
